# Generated by Django 3.2.8 on 2022-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_kg', models.FloatField()),
                ('height_in_cm', models.FloatField()),
            ],
        ),
    ]
