# Generated by Django 3.2.8 on 2022-03-19 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackers', '0004_alter_bmidata_bmi_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmidata',
            options={'verbose_name': 'BMI'},
        ),
        migrations.AddField(
            model_name='bmidata',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bmidata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
