# Generated by Django 3.2.8 on 2022-03-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_alter_bmidata_bmi_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmidata',
            options={'verbose_name': 'BMI'},
        ),
        migrations.AddField(
            model_name='bmidata',
            name='username',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
