# Generated by Django 3.2.8 on 2022-03-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='user',
        ),
    ]
