# Generated by Django 3.2.8 on 2022-04-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='address',
            name='organizationcontact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.organizationcontact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='address',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.practitioner'),
        ),
        migrations.AlterField(
            model_name='address',
            name='relatedperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_person_address', to='account.relatedperson'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='account.annotation'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availableTime', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='account.practitioner'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='organizationcontact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.organizationcontact'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='relatedperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_person_contact_point', to='account.relatedperson'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='healthcarecategory',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='hoursofoperation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoursOfOperation', to='account.location'),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='account.contact'),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='oganizationcontact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='account.organizationcontact'),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='account.practitioner'),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='relatedperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_person_name', to='account.relatedperson'),
        ),
        migrations.AlterField(
            model_name='link',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='location',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maritalStatus', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode', to='account.location'),
        ),
        migrations.AlterField(
            model_name='notavailabletime',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notAvailable', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='operationalstatus',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operationalStatus', to='account.location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='careteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managingOrganization', to='account.careteam'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providedBy', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managingOrganization', to='account.location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onBehalfOf', to='account.participant'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managingOrganization', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to='account.qualification'),
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='account.organization'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantrole',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='account.participant'),
        ),
        migrations.AlterField(
            model_name='period',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.address'),
        ),
        migrations.AlterField(
            model_name='period',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.contact'),
        ),
        migrations.AlterField(
            model_name='period',
            name='contactpoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.contactpoint'),
        ),
        migrations.AlterField(
            model_name='period',
            name='humanname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.humanname'),
        ),
        migrations.AlterField(
            model_name='period',
            name='notavailabletime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='during', to='account.notavailabletime'),
        ),
        migrations.AlterField(
            model_name='period',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.participant'),
        ),
        migrations.AlterField(
            model_name='period',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.qualification'),
        ),
        migrations.AlterField(
            model_name='physicallocationtype',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physicalType', to='account.location'),
        ),
        migrations.AlterField(
            model_name='position',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='account.location'),
        ),
        migrations.AlterField(
            model_name='program',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='account.practitioner'),
        ),
        migrations.AlterField(
            model_name='qualificationcodeableconcept',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='account.qualification'),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasonCode', to='account.participant'),
        ),
        migrations.AlterField(
            model_name='referralmethod',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referralMethod', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='relatedperson',
            name='relationship',
            field=models.CharField(blank=True, choices=[('C', 'Emergency Contact'), ('E', 'Employer'), ('F', 'Federal Agency'), ('I', 'Insurance Company'), ('N', 'Next-of-Kin'), ('S', 'State Agency'), ('U', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovisioncode',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceProvisionCode', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='status',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='account.location'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='careteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='account.careteam'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='careteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.careteam'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.contact'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.location'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.patient'),
        ),
        migrations.AlterField(
            model_name='telecom',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom', to='account.practitioner'),
        ),
        migrations.AlterField(
            model_name='type',
            name='healthcareservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='account.healthcareservice'),
        ),
        migrations.AlterField(
            model_name='types',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='account.location'),
        ),
    ]
