# Generated by Django 3.2.8 on 2022-04-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletime',
            old_name='availabelEndTIme',
            new_name='availabelEndTime',
        ),
        migrations.RenameField(
            model_name='availabletime',
            old_name='availableStartTIme',
            new_name='availableStartTime',
        ),
        migrations.CreateModel(
            name='PhysicalLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('si', 'Site'), ('bu', 'Building'), ('wi', 'Wing'), ('wa', 'Ward'), ('lvl', 'Level'), ('co', 'Corridor'), ('ro', 'Room'), ('bd', 'Bed'), ('ve', 'Vehicle'), ('ho', 'House'), ('ca', 'Cabinet'), ('rd', 'Road'), ('area', 'Area'), ('jdn', 'Jurisdiction')], max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicalType', to='account.location')),
            ],
        ),
    ]
