# Generated by Django 3.2.8 on 2022-03-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_customer_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.period'),
        ),
    ]
