# Generated by Django 3.2.8 on 2022-04-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_participant_careteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='careteam',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='account.careteam')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='note',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='account.note'),
            preserve_default=False,
        ),
    ]
