# Generated by Django 3.2.8 on 2022-03-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0003_alter_address_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Practitioner',
        ),
    ]
