# Generated by Django 3.2.8 on 2022-03-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_communication_contact_contactpoint_deceased_humanname_link_maritalstatus_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpoint',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.period'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name=50),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='system',
            field=models.CharField(blank=True, choices=[('1', 'phone'), ('2', 'fax'), ('3', 'email'), ('4', 'pager'), ('5', 'url'), ('6', 'sms')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='use',
            field=models.CharField(blank=True, choices=[('1', 'Mobile'), ('2', 'Work'), ('3', 'Home'), ('4', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
