# Generated by Django 3.2.8 on 2022-04-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_contact_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasoncode',
            name='participant',
        ),
        migrations.AddField(
            model_name='period',
            name='careteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period', to='account.careteam'),
        ),
        migrations.AddField(
            model_name='reasoncode',
            name='careteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasonCode', to='account.careteam'),
        ),
    ]
