# Generated by Django 3.2.8 on 2022-04-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_practitioner_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='occupation',
        ),
    ]
