# Generated by Django 3.2.8 on 2022-03-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220318_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpoint',
            name='period',
        ),
        migrations.RemoveField(
            model_name='period',
            name='user',
        ),
    ]
