# Generated by Django 3.2.8 on 2022-03-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220320_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.period'),
        ),
    ]
