# Generated by Django 3.2.8 on 2022-04-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220405_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistermodel',
            name='patient',
        ),
    ]
