# Generated by Django 3.2.8 on 2022-04-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_patientregistermodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistermodel',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='account.patient'),
        ),
    ]
